import {
  Alignment,
  BlockQuote,
  Bold,
  ClassicEditor,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  HorizontalLine,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  List,
  ListProperties,
  Paragraph,
  RemoveFormat,
  SimpleUploadAdapter,
  SpecialCharacters,
  SpecialCharactersEssentials,
  Strikethrough,
  Table,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  Underline,
  Undo,
} from 'ckeditor5'
import { csrfToken } from './useRichText.js'
import { IndentDirection, TextDirection } from './ckeditorTextDirection.js'

const FONT_COLOR_PALETTE = [
  { color: '#0B1F3A', label: 'Navy' },
  { color: '#1B4F9C', label: 'Royal Blue' },
  { color: '#7AC142', label: 'Green' },
  { color: '#4B5563', label: 'Dark Gray' },
  { color: '#FFFFFF', label: 'White', hasBorder: true },
  { color: '#DC2626', label: 'Red' },
]

export function createRichTextEditorConfig({ placeholder = '', contentLanguage = 'en' } = {}) {
  return {
    licenseKey: 'GPL',
    placeholder,
    language: {
      ui: 'en',
      content: contentLanguage,
    },
    plugins: [
      Essentials,
      Undo,
      Bold,
      Italic,
      Underline,
      Strikethrough,
      RemoveFormat,
      Heading,
      FontSize,
      FontFamily,
      FontColor,
      FontBackgroundColor,
      Alignment,
      TextDirection,
      Link,
      List,
      ListProperties,
      Indent,
      IndentBlock,
      IndentDirection,
      Paragraph,
      BlockQuote,
      HorizontalLine,
      SpecialCharacters,
      SpecialCharactersEssentials,
      Image,
      ImageCaption,
      ImageResize,
      ImageStyle,
      ImageToolbar,
      ImageUpload,
      SimpleUploadAdapter,
      Table,
      TableToolbar,
      TableProperties,
      TableCellProperties,
      TableColumnResize,
    ],
    toolbar: {
      items: [
        'undo', 'redo',
        '|',
        'heading',
        '|',
        'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor',
        '|',
        'bold', 'italic', 'underline', 'strikethrough', 'removeFormat',
        '|',
        'alignment', 'textDirection', 'ltr', 'rtl',
        '|',
        'link', 'bulletedList', 'numberedList', 'outdent', 'indent',
        '|',
        'blockQuote', 'horizontalLine', 'specialCharacters',
        '|',
        'insertTable', 'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties',
        '|',
        'uploadImage',
      ],
      shouldNotGroupWhenFull: true,
    },
    heading: {
      options: [
        { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
        { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
        { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
        { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
      ],
    },
    fontSize: {
      options: ['small', 'default', 16, 18, 20, 24, 28, 32],
      supportAllValues: false,
    },
    fontFamily: {
      options: [
        'default',
        'Cairo, sans-serif',
        'Lato, sans-serif',
        'Arial, Helvetica, sans-serif',
        'Tahoma, Geneva, sans-serif',
        'Georgia, serif',
      ],
      supportAllValues: false,
    },
    fontColor: {
      colors: FONT_COLOR_PALETTE,
    },
    fontBackgroundColor: {
      colors: FONT_COLOR_PALETTE,
    },
    alignment: {
      options: ['left', 'center', 'right', 'justify'],
    },
    link: {
      addTargetToExternalLinks: true,
      defaultProtocol: 'https://',
    },
    image: {
      toolbar: [
        'imageTextAlternative',
        'toggleImageCaption',
        '|',
        'imageStyle:inline',
        'imageStyle:block',
        'imageStyle:side',
        'imageStyle:alignLeft',
        'imageStyle:alignCenter',
        'imageStyle:alignRight',
        '|',
        'resizeImage',
        'linkImage',
      ],
      resizeOptions: [
        { name: 'resizeImage:original', label: 'Original', value: null },
        { name: 'resizeImage:25', label: '25%', value: '25' },
        { name: 'resizeImage:50', label: '50%', value: '50' },
        { name: 'resizeImage:75', label: '75%', value: '75' },
      ],
      resizeUnit: '%',
    },
    indentBlock: {
      offset: 40,
      unit: 'px',
    },
    list: {
      properties: {
        styles: {
          listStyleTypes: {
            bulleted: ['disc', 'circle', 'square'],
            numbered: ['decimal', 'lower-alpha'],
          },
        },
        startIndex: true,
        reversed: true,
      },
    },
    table: {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableProperties',
        'tableCellProperties',
      ],
      tableProperties: {
        defaultProperties: {
          borderStyle: 'none',
        },
      },
      tableCellProperties: {
        defaultProperties: {
          borderStyle: 'none',
        },
      },
    },
    simpleUpload: {
      uploadUrl: route('rich-text-images.store'),
      withCredentials: true,
      headers: {
        'X-CSRF-TOKEN': csrfToken(),
        Accept: 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
      },
    },
  }
}

export { ClassicEditor }
